import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/client";
import "./globals.css";
import { SandPackCSS } from "@/components/sandpack-styles";
import { Toaster } from "sonner";
import SideBar from "@/components/SideBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <SandPackCSS />
      </head>
      <body className={`${montserrat.className} antialiased`}>
        <TRPCReactProvider>
          <Toaster />
          <div className="flex flex-row w-full overflow-x-hidden">
            <SideBar />
            <main className="flex-1">{children}</main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
